# Inspired by https://docs.docker.com/compose/django/
version: '3'

services:
  db:
    image: mariadb:10.5-bionic
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-sosecret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-pta_export}
      MYSQL_USER: ${MYSQL_USER:-pta_export}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pta_export}
    volumes:
      - db:/var/lib/mysql
      - ./docker-init-db.sql:/docker-entrypoint-initdb.d/init_db.sql

  web:
    build: .
    image: regexit/pta-export:latest
    environment:
      DJANGO_SETTINGS_MODULE: pta_export.conf.docker
      SECRET_KEY: ${SECRET_KEY:-dvoyzzh@eqlv0=gxal%kb3106dmd4=nx)2#2+czs-=-#p9q_(_}
      DB_NAME: ${MYSQL_DATABASE:-pta_export}
      DB_USER: ${MYSQL_USER:-pta_export}
      DB_PASSWORD: ${MYSQL_PASSWORD:-pta_export}
    ports:
      - ${WEB_PORT:-8000}:8000
    depends_on:
      - db


volumes:
  db:
