# Inspired by https://docs.docker.com/compose/django/
version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD:-overrideme}
      POSTGRES_DB: ${DJANGO_DB_NAME:-ocpta}
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker-init-db.sql:/docker-entrypoint-initdb.d/init_db.sql

  web:
    build: .
    image: regexit/pta-export:latest
    environment:
      DJANGO_SETTINGS_MODULE: pta_export.conf.docker
      SECRET_KEY: ${SECRET_KEY:-dvoyzzh@eqlv0=gxal%kb3106dmd4=nx)2#2+czs-=-#p9q_(_}

      DJANGO_DB_NAME: ${DJANGO_DB_NAME:-ocpta}
      DJANGO_DB_USER: ${DJANGO_DB_USER:-postgres}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD:-overrideme}
      DJANGO_DB_HOST: ${DJANGO_DB_HOST:-postgres}

      OCPTA_DB_USER: ${OCPTA_DB_USER:-pta_export}
      OCPTA_DB_PASSWORD: ${OCPTA_DB_PASSWORD:-pta_export}
      OCPTA_DB_HOST: ${OCPTA_DB_HOST:-db}
    ports:
      - ${WEB_PORT:-8000}:8000
    depends_on:
      - postgres


volumes:
  db:
